### ISSUE TITLE
[1.2.0] UE4 activity no longer appears on WakaTime

### ISSUE THREAD

**Issue by simonSlamka** [Pozitrone/WakaTimeForUE4#19] opened 2021-08-01 14:38 UTC
Today I accidentally noticed that my UE4 activity is not being logged!

WakaTime receives the heartbeats, but they don't appear on the dashboard, so perhaps the raw heartbeat data is faulty.

The reason could be that the heartbeat's _is_write_ param is null, but I'm not sure.

https://wakatime.com/api/v1/users/current/heartbeats?date=2021-08-01&show=machine_name,user_agent

To view raw heartbeat data for the currently logged-in account (change the date as appropriate).

**Comment by simonSlamka** [comment] 2021-08-01 14:44
Found the issue. You **need to** write _at least_ one _coding_ category heartbeat per session for it to appear on WakaTime. I tried it directly out of cmd and now all my UE4 activity for today appeared.

**Comment by simonSlamka** [comment] 2021-08-01 14:44
Make sure you do this once in a while, possibly when exiting the engine.

**Comment by simonSlamka** [comment] 2021-08-01 15:21
When submitting a heartbeat on save, it seems to be necessary to include _--write true_, so WakaTime understands and counts the activity correctly.

**Comment by simonSlamka** [comment] 2021-08-01 15:41
> 
> 
> When submitting a heartbeat on save, it seems to be necessary to include _--write true_, so WakaTime understands and counts the activity correctly.

Ah, you have it there. Well, for me it doesn't work. That boolean is false when even when saving.

**Comment by Pozitrone** [comment] 2021-08-02 07:35
I believe I started working with it, however the engine was for some reason crashing, when I was using the --write; however, I can test if thats still the case (It was crashing the VR project template, so there might be a weird collision?).

**Comment by Pozitrone** [comment] 2021-08-02 07:37
I assume I never encountered this issue, as I never used just UE4 during a day; it was always combined with other IDE, or it was after work, which naturally already submitted the heartbeats with --write.

I will try to add it into the save event, as that feels like where it should be.

**Comment by Pozitrone** [comment] 2021-08-03 07:35
Tried it with the latest version, however, I am unable to reproduce the issue. (however, I do have cmd `$ wakatime`)
![image](https://user-images.githubusercontent.com/36227512/127976294-6e56b3f7-6733-48f0-8931-590d4c4f6f14.png)
So I assume this only happens without it. As I promised, I will look into the plugin soon, to figure out this issue.

If it is no longer crashing the VR template, I will just enable --write for file save event.

**Comment by simonSlamka** [comment] 2021-08-03 09:45
I modified my local copy to fix the issue by forcing the _--write_ param at all times, though I haven't used the VR template, so can't say if it's crashing or not.

**Comment by Pozitrone** [comment] 2021-08-04 07:23
Managed to get my time tracked properly even without any kind of wakatime installed (which means the plugin downloaded it on its own).

Sadly, I dont have much time to test it now, but I will get to it... soon... I promise!

**Comment by Pozitrone** [comment] 2021-08-05 15:33
Checked within the VR template after enabling --write in c99de9c73c0cf8d0f4552f490f047e43ebd083c5.
Everything looks correct, closing the issue as solved with version 1.2.1

**Closed by Pozitrone** 2021-08-05 15:33 UTC
Labels: 🐛 Bug
